### ISSUE TITLE
上传文件夹/文件存在同名

### ISSUE THREAD

**Issue by mayishidai** [aoaostar/alidrive-uploader-for-baota#12]
上传备份文件夹/文件的时候，会出现，原本是一个文件夹的内容，会被分割存放为同名目录的其他文件夹下
![image](https://user-images.githubusercontent.com/20534392/167236417-f1e45e6c-06f6-4dcd-9899-604e2681286f.png)
![image](https://user-images.githubusercontent.com/20534392/167236430-1b08abbf-6e92-4179-8b46-5e59eb7a507c.png)

**Comment by aoaostar** [comment]
该问题应该在该仓库：https://github.com/aoaostar/alidrive-uploader  

https://github.com/aoaostar/alidrive-uploader/commit/60e82f4764b32a14ae2a7035ac08e7efe4a93197
